export const MATCH_NAME_REQUEST = "MATCH_NAME_REQUEST";
export const MATCH_NAME_SUCCESS = "MATCH_NAME_SUCCESS";
export const MATCH_NAME_FAIL = "MATCH_NAME_FAIL";

export const MATCH_DATA_REQUEST = "MATCH_DATA_REQUEST";
export const MATCH_DATA_SUCCESS = "MATCH_DATA_SUCCESS";
export const MATCH_DATA_FAIL = "MATCH_DATA_FAIL";
